# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development: 
  secret_key_base: f68c0637daefeb2205d00820e483868de7d0d01e8483e7e340aaec8517df0b444f0985d1c875f526a2012c8ceab9a150af36116b788346bd143c00b7248c4712
  rollbar_access_token: 88ca28cdf89540818986e1a08ffdbad6
  rollbar_client_access_token: 
  rollbar_environment: development
  aws_access_key_id: AKIAJVATG6VBRX53SGRA
  aws_secret_access_key: 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
  aws_region: us-east-1
  aws_bucket: eagle-assets-dev
  allowed_api_keys: ['Swagger_feb2205d00820', 'dev_e483868de7d0d']
  dev_url: <%= ENV["DEV_URL"] %>
  api_url: <%= ENV["REACT_APP_API_DOMAIN"] %>
  api_version: <%= ENV["REACT_APP_API_VERSION"] %>
  debugging: <%= ENV["CUSTOM_DEBUGGING"] %>

test:
  secret_key_base: a921c872941fc724ed4af4c087b84d2186e93252a784486db4efbd5ab8284a980e4878c06104bdb622c962e404f0b54b1080e390256df0949e0e96056ee493e6
  debugging: false

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  rollbar_client_access_token: <%= ENV['ROLLBAR_CLIENT_ACCESS_TOKEN'] %>
  rollbar_environment: staging
  # aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  # aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  # aws_bucket: us-east-1
  # aws_bucket_name: <%= ENV["AWS_BUCKET_NAME"] %>
  aws_access_key_id: AKIAJVATG6VBRX53SGRA
  aws_secret_access_key: 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
  aws_region: us-east-1
  aws_bucket: eagle-assets-staging
  allowed_api_keys: <%= ENV["ALLOWED_API_KEYS"] %>
  dev_url: <%= ENV["DEV_URL"] %>
  api_url: <%= ENV["REACT_APP_API_DOMAIN"] %>
  api_version: <%= ENV["REACT_APP_API_VERSION"] %>
  debugging: <%= ENV["CUSTOM_DEBUGGING"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  rollbar_client_access_token: <%= ENV['ROLLBAR_CLIENT_ACCESS_TOKEN'] %>
  rollbar_environment: production
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_region: us-east-1
  aws_bucket: <%= ENV["AWS_BUCKET_NAME"] %>
  allowed_api_keys: <%= ENV["ALLOWED_API_KEYS"] %>
  dev_url: <%= ENV["DEV_URL"] %>
  api_url: <%= ENV["REACT_APP_API_DOMAIN"] %>
  api_version: <%= ENV["REACT_APP_API_VERSION"] %>
  debugging: <%= ENV["CUSTOM_DEBUGGING"] %>
  
