# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development: 
  secret_key_base: f68c0637daefeb2205d00820e483868de7d0d01e8483e7e340aaec8517df0b444f0985d1c875f526a2012c8ceab9a150af36116b788346bd143c00b7248c4712
  rollbar_access_token: 
  rollbar_client_access_token: 
  rollbar_environment: development
  allowed_api_keys: ['Swagger_feb2205d00820', 'dev_e483868de7d0d']
  # dev_url: http://dev.eazyo.local:5000
  api_url: http://localhost:5000
  debugging: <%= ENV["CUSTOM_DEBUGGING"] %>

test:
  secret_key_base: a921c872941fc724ed4af4c087b84d2186e93252a784486db4efbd5ab8284a980e4878c06104bdb622c962e404f0b54b1080e390256df0949e0e96056ee493e6
  rollbar_access_token: 
  rollbar_client_access_token: 
  rollbar_environment: development
  # dev_url: http://dev.eazyo.local:5000
  # api_url: http://api.eazyo.local:5000
  debugging: false

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  rollbar_client_access_token: <%= ENV['ROLLBAR_CLIENT_ACCESS_TOKEN'] %>
  rollbar_environment: staging
  allowed_api_keys: <%= ENV["ALLOWED_API_KEYS"] %>
  # dev_url: http://dev.eazyo.local:5000
  api_url: <%= ENV["API_URL"] %>
  debugging: <%= ENV["CUSTOM_DEBUGGING"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  rollbar_client_access_token: <%= ENV['ROLLBAR_CLIENT_ACCESS_TOKEN'] %>
  rollbar_environment: production
  # dev_url: http://dev.eazyo.local:5000
  # api_url: http://api.eazyo.local:5000
  debugging: <%= ENV["CUSTOM_DEBUGGING"] %>
  
